### ISSUE TITLE
chime soundboard is down

### ISSUE THREAD

**Issue by koaning** [MaxHalford/chime#3]
<img width="895" alt="image" src="https://user-images.githubusercontent.com/1019791/95359377-5f497e00-08ca-11eb-94e8-ce3efa54c6d7.png">

**Comment by MaxHalford** [comment]
I've literally just tried it out and it's working for me: [https://streamable.com/0ekhtf](https://streamable.com/0ekhtf). Weird!

Maybe a browser issue? If so I assume it's an issue that's coming from Streamlit.

Edit: Indeed it seems that the `audio` widget from Streamlit doesn't work on Safari. I've opened an [issue](https://github.com/streamlit/streamlit/issues/2113) on the Streamlit repo to see what's what.

**Comment by koaning** [comment]
Yeah it seems to be working now. 

One question; why not host these as static files on something like netlify? The load times are bound to be much faster.

**Comment by MaxHalford** [comment]
Well I didn't really think about it. I thought that using a Python runtime is cool because it acts as a unit test by actually running `chime` and not just the sounds themselves. As for the load times, Heroku is pretty fast as long as there's enough users, no? The app is spin downed if nobody goes on the site, so it's slow when the usage is sporadic.

But you're right, it would be faster. I might consider it in the future if the project's user base grows :)

**Comment by MaxHalford** [comment]
Actually the soundboard is still not working on Safari so I'll keep this open while it isn't.

**Comment by MaxHalford** [comment]
This will be fixed with the release of streamlit 0.68.2; I've tested the nightly build and it worked. I've update the streamlit requirement in poetry.
